// functions/config/analysis/user_analysis.js

const {
  USER_ANALYSIS_RESULT_FIELDS,
  USER_ANALYSIS_WEIGHT_PROJECTION_FIELDS,
} = require("../firebase/user_analysis_schema");

const USER_ANALYSIS_CONFIG = {
  DEFAULT_DAILY_SUMMARY_DAY_COUNT: 7,
  CALORIES_PER_KG_BODY_WEIGHT: 7700,
  FOOD_CONSUMPTION_REVIEW_MAX_ENTRIES: 50,
  WEIGHT_CHANGE_PROJECTION_PERIODS: [
    {
      [USER_ANALYSIS_WEIGHT_PROJECTION_FIELDS.PERIOD_LABEL]: "1 month",
      [USER_ANALYSIS_WEIGHT_PROJECTION_FIELDS.DAYS]: 30,
    },
    {
      [USER_ANALYSIS_WEIGHT_PROJECTION_FIELDS.PERIOD_LABEL]: "3 months",
      [USER_ANALYSIS_WEIGHT_PROJECTION_FIELDS.DAYS]: 90,
    },
    {
      [USER_ANALYSIS_WEIGHT_PROJECTION_FIELDS.PERIOD_LABEL]: "6 months",
      [USER_ANALYSIS_WEIGHT_PROJECTION_FIELDS.DAYS]: 180,
    },
  ],
};

const USER_ANALYSIS_FOOD_CONSUMPTION_REVIEW_CONTEXT_FIELDS = {
  FOOD_CONSUMPTION_ENTRIES: "foodConsumptionEntries",
  DAILY_CALORIE_SUMMARIES:
    USER_ANALYSIS_RESULT_FIELDS.DAILY_CALORIE_SUMMARIES,
  DAILY_CALORIES_REQUIRED:
    USER_ANALYSIS_RESULT_FIELDS.DAILY_CALORIES_REQUIRED,
  DAILY_AVERAGE_CALORIES_CONSUMED:
    USER_ANALYSIS_RESULT_FIELDS.DAILY_AVERAGE_CALORIES_CONSUMED,
  DAILY_AVERAGE_CALORIE_DIFFERENCE:
    USER_ANALYSIS_RESULT_FIELDS.DAILY_AVERAGE_CALORIE_DIFFERENCE,
};

module.exports = {
  USER_ANALYSIS_CONFIG,
  USER_ANALYSIS_FOOD_CONSUMPTION_REVIEW_CONTEXT_FIELDS,
};
